name: biobb_wf_ligand_parameterization
channels:
  - conda-forge
  - bioconda
dependencies:
  - biobb_io==5.1.0
  - biobb_chemistry==5.1.0
  - jupyterlab=3.6
  - nodejs=16
  - ipywidgets=7
  - nglview